
DEF T_TYPE_STOP = 0
DEF T_TYPE_VOID = 1
DEF T_TYPE_BOOL = 2
DEF T_TYPE_BYTE = 3
DEF T_TYPE_I08 = 3
DEF T_TYPE_DOUBLE = 4
DEF T_TYPE_I16 = 6
DEF T_TYPE_I32 = 8
DEF T_TYPE_I64 = 10
DEF T_TYPE_STRING = 11
DEF T_TYPE_UTF7 = 11
DEF T_TYPE_BINARY = 11
DEF T_TYPE_STRUCT = 12
DEF T_TYPE_MAP = 13
DEF T_TYPE_SET = 14
DEF T_TYPE_LIST = 15
DEF T_TYPE_UTF8 = 16
DEF T_TYPE_UTF16 = 17

ctypedef unsigned char byte
